title:            Small stuff
tagline:          A short tagline
description:      Describe your website.
# Your site's domain goes here. Leave localhost server or blank when working locally.
url:              http://szilardhuber.github.io

# Owner/author information
owner:
  name:           Szil√°rd Huber
  avatar:         bio-photo.jpg
  bio:            "Coding craftsman who prefers simple solutions. Now working on www.virtdb.com; previously R&D manager @logmein"
  email:          szilard.huber@aisoft.hu
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  twitter:        szilardhuber
  facebook:       
  github:         szilardhuber
  linkedin:       
  instagram:      
  lastfm:         
  tumblr:         
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    https://plus.google.com/113111609097304837410

# Analytics and webmaster tools stuff goes here
google_analytics:   UA-46741385-1
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:        

# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: /about/
  - title: Articles
    url: /articles/
  - title: Legal
    url: /legal/

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Budapest
future:      true
highlighter: rouge

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

plugins:
  - jekyll-gist
  - jekyll-paginate

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "vendor", "vendor/bundle"]
